chainer/chainerui

README.md
`git clone git@github.com:chainer/chainerui.git` requires a github accout. With `https://github.com/chainer/chainerui.git`, everyone can clone this repository without accounts.
=> Use https instead of git in README

chainerui/__init__.py
ChainerUI wouldn't start on Python 2.7.x.
```bash
$ python --version
Python 2.7.12
$ chainerui db create
Traceback (most recent call last):
File "/home/kuni/tmp/chaineruitest/bin/chainerui", line 11, in <module>
sys.exit(main())
File "/home/kuni/tmp/chaineruitest/local/lib/python2.7/site-packages/chainerui/app.py", line 105, in main
args.handler(args)
File "/home/kuni/tmp/chaineruitest/local/lib/python2.7/site-packages/chainerui/app.py", line 28, in db_handler
create_db()
File "/home/kuni/tmp/chaineruitest/local/lib/python2.7/site-packages/chainerui/__init__.py", line 39, in create_db
os.makedirs(DB_FILE_DIR, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'
```
The argument `exist_ok=True` of `os.makedirs` is supported by only `Python>=3.5`.
So I rewrote …
=> Fix db directory creation error on Python 2.7

chainerui/utils/save_args.py
I encountered the following error when using dict as conditions.
```
File "/Users/shinsuke.sugaya/.anyenv/envs/pyenv/versions/3.6.3/lib/python3.6/site-packages/chainerui/utils/save_args.py", line 21, in save_args
args_dict = {k: str(v) for k, v in args.items()}
UnboundLocalError: local variable 'args' referenced before assignment
```
=> Pass dict type conditions to save_args

.circleci/config.yml, requirements.txt
If Flask that includes pallets/flask#2193 is released, this PR isn't need to merged.
=> Workaround for pallets/flask#2193

chainerui/utils/__init__.py, chainerui/utils/log_report.py, examples/train_mnist_custom_loop.py, tests/utils_tests/test_log_report.py
refs #27 
- the util class set 'elapsed_time' automatically, but 'epoch' and 'iteration' is not set.
- example code is based on [train_mnist_custom_loop.py](chainer/examples/mnist/train_mnist_custom_loop.py)
=> Log report util class to support train loop without Trainer

chainerui/__init__.py
I stopped pretty printing at JSON building.
This is 2x faster! You can feel speedup if the log is huge (ex. >30MB).
=> 2x faster JSON building

frontend/src/components/result/Commands.jsx
Fix #7.
I hid `executed_at` that is empty instead of replacing to "Waiting".
As the reason:
* The user can know the status in response status field.
* The message is difficult because the status gets "before scheduling" or "after scheduling". 
Before:
After:
=> Hide "Invalid Date"

tests/test_api.py
API test shows example directory as test project, but it is inconvenient to run state test in future. For example, we will add job status to improve error message when executing commands. API test requires to change the status.
=> Stop seeing example directory on API test

chainerui/extensions/commands_extension.py, chainerui/utils/__init__.py, chainerui/utils/commands_state.py, chainerui/views/result_command.py, requirements.txt, tests/extensions_tests/test_commands_extension.py, tests/test_api.py
depends #59 , refs #7, #45
On this PR, when training job is not run, response returns `400` code and not call `CommandsExtension` instance. So error result is not shown for commands history table.
=> [WIP] Commands are executed only when training job is running

chainerui/views/result.py, tests/test_api.py
fixes #30 
when project is not found, return 404 on `projects/{id}/result/**` API
=> fix 404 logic on result API

tests/test_api.py
refs #82 
- split project, result api and command post api
- use one result directory to test commands
=> fix command post test, not depends on id ordering

frontend/src/components/result/ResultSummary.jsx, frontend/src/containers/PlotContainer.jsx
Fix #66 
I added `episode` and `step` keys to the summary pane like below.
This change enables us to add keys easily. We just edit `keyOptions`.
=> Add `episode` and `step` to summary pane

.travis.yml, requirements.txt
- Flask < 1.0
- chainer >= 3.0.0 (not support v2)
- remove unnecessary version fix on CI
=> Modify dependencies' version

chainerui/models/log.py, tests/model_tests/test_log.py
The current version of the code does not work in case the log file contains anything else than numbers (`integers` or `floats`). It might happen that some users store values like `lists` in their log.
This PR adds a check that filters all values that are not a number, hence allowing such values in the log file.
=> do not crash if logs contain anything else than numbers or strings

chainerui/models/project.py, chainerui/models/result.py, chainerui/tasks/collect_results.py, chainerui/tasks/crawl_result.py, chainerui/views/result.py, chainerui/views/result_command.py
- remove to load `Result` model on `crawl_results`
- remove to load `CommandItem` on `crawl_results`
- stop to use preloaded import path
- `from chainerui.tasks import collect_results` -> `from chainerui.tasks.collect_result import collect_results`
fixes #108
=> Resolve circular reference

chainerui/utils/save_args.py, tests/utils_tests/test_save_args.py
This PR may contains needs to be discussed.
I want to use `save_args` for constructing a model in inference.
`args` often contains a lot of model parameters.
In my situation, I have a list object for model parameters like below
```python
class BiLSTM_CRF(chainer.Chain):
def __init__(self, n_elems, dims, n_label, hidden_dim):
super(BiLSTM_CRF, self).__init__()
feature_dim = sum(dims)
print(feature_dim)
```
And I add `n_elems` and `dims` into args and call `save_args`.
`save_args` convert each value in args to `string`.
So I got dict object like below.
```json
{
"n_elems": "[2073, 18]",
"dims": "[50, 50]",
"n_label": "17",
"hidden_dim": "50"
}
```
We can see `n_elems` and `dims' are the string, which contains the list of integer.
I want `n_elems` and `dims` to be list of integer directly. …
=> Stop str() for elements in args

chainerui/extensions/image_reporter_extension.py, chainerui/summary.py, tests/extensions_tests/test_image_reporter_extension.py, tests/test_summary.py
`summary.image` accepts batched image on default, and `ndim` is `3` then `ImageReport` deal with the images as grayscale image. When target image is not batched, set `batched` flag as `False`.
=> Support grayscale image on ImageReport

frontend/src/containers/PlotContainer.jsx
ChainerUI draws in a single column on narrow screens like smartphones.
At that time, I changed it to display a chart and a table column first.
Before:
After:
=> Swap a left column for a right column

chainerui/__init__.py, chainerui/app.py, requirements.txt
Resolve #107 
Use production server by default.
When we run `chainerui server` , ChainerUI runs with [gevent](http://www.gevent.org/api/gevent.pywsgi.html#module-gevent.pywsgi) production server.
When we run `chainerui server --debug` , ChainerUI runs with flask development server (same behavior as current master branch)
I chose `gevent` from "Self-hosted options" in [Deployment Options](http://flask.pocoo.org/docs/dev/deploying/) .
=> Fix development server warning

.travis.yml
- use build cache to include frontend modules in sdist file
- deployed modules are made using npm@6 so far, so update npm version manually for deploying
- appveyer has already use npm 6.3.0, so skip to designate version number
=> fix deploy section, update npm

chainerui/migration/versions/c29d1b4b67fe_add_result_log_index.py
If a project has many results, searching cost of logs cannot be ignored. This PR reduces the searching cost by indexing.
Benchmark
- test data:1 project, 100 results, each results have 300 log items
- before
- 0.2~0.3 sec per fetching logs to result object
- after
- 0.01~0.03 sec
=> add index to reduce log search cost

chainerui/__init__.py, chainerui/app.py, chainerui/database.py, chainerui/migration/env.py, chainerui/migration/versions/4e779a5fc57e_add_is_unregistered_to_result.py, chainerui/models/argument.py, chainerui/models/asset.py, chainerui/models/bindata.py, chainerui/models/command.py, chainerui/models/log.py, chainerui/models/project.py, chainerui/models/result.py, chainerui/models/snapshot.py, chainerui/tasks/collect_images.py, chainerui/tasks/collect_results.py, chainerui/tasks/crawl_result.py, chainerui/utils/db_revision.py, chainerui/views/project.py, chainerui/views/result.py, chainerui/views/result_command.py, chainerui/views/result_image.py, tests/migration_tests/versions_tests/test_alter_log_data_type.py, tests/tasks_tests/test_collect_images.py, tests/test_api.py, tests/test_app.py, tests/test_init.py, tests/utils_tests/test_db_revision.py
This PR is for supporting other DB, such as MySQL or PostgreSQL
- split `DB_*` to `chainerui.db`
- DB engine and session are set in `chainerui.db`
- add `--db` option, ex: `chainerui --db <db-url> server`
- if `--db` is empty, use SQLite
- fix miner bug
- [wrong table name](https://github.com/chainer/chainerui/blob/c75f394a8f2e60b028c9d337ecac5255449953ec/chainerui/migration/versions/4e779a5fc57e_add_is_unregistered_to_result.py#L26)
- refactoring `test_app.py`, simplified
I'll sent another PR
- document
- add test using other DB
=> Add DB option enable to select other DB

.travis.yml, appveyor.yml, chainerui/__init__.py, chainerui/app.py, chainerui/logging.py, chainerui/tasks/crawl_result.py, requirements.txt, setup.cfg, tests/test_app.py, tests/test_logging.py
ChainerUI uses Flask's default logging system, this causes unable to control logging style and output format. This PR introduces own logger to control logging system. ChainerUI will apply structured logging in future, but at first, this PR (almost) maintains current log format.
**Changed points**
- Omit application name and eager mode log sentence on debug mode. 
- example: ` * Serving Flask app "chainerui" (lazy loading)`
- add content length and response time on debug mode.
- these numbers have been viewed on production mode.
This PR replaced logging using `print` function only on server side, `print` has still remain on client logging such as `chainerui db create`.
=> Replace logging system on server side

chainerui/database.py
avoid to print stacktrace on the following cases.
- not install DB driver
- cannot connect to DB
=> Add connection checker to external DB

docs/source/external_db.rst, docs/source/index.rst, docs/source/install.rst, docs/source/reference/cmd.rst
- add external db chapter
- add `--db` command section
- other small fix
=> Add documents about database option

frontend/src/components/ExperimentsTableConfigurator.jsx
=> Add word-break into ExperimentsTableConfigurator

tests/conftest.py, tests/extensions_tests/test_commands_extension.py, tests/extensions_tests/test_image_reporter_extension.py, tests/models_tests/test_result.py, tests/tasks_tests/test_collect_images.py, tests/tasks_tests/test_crawl_result.py, tests/test_api.py, tests/test_app.py, tests/utils_tests/test_log_report.py, tests/utils_tests/test_save_args.py
some tests use temporary directory using `tempfile` module, this PR fixes to aggregate the process.
* use `pytest.fixture`, all test can use `func_dir` fixture or `TempDirTetsCase` class
* remove `setUp` and `tearDown` to create temporary directories
* replace `tmpdir` to `func_dir`, `func_dir` is customized `tmpdir` fit for ChainerUI tests
* current tests use class method even if targets are function (not class module), modify them as "function"
=> Refactoring tests, aggregate temporary directory

setup.cfg
=> Fix minversion as string type to pass pytest's version check

frontend/src/components/LogVisualizer.jsx, frontend/src/components/LogVisualizerTooltip.jsx, frontend/src/styles.css
fixes #202 
- revert `LogVisualizerTooltip` component
- show only values, result id and key name is hidden
=> Restore tooltip option on line chart

setup.cfg
Reverts chainer/chainerui#204
pytest 3.10.1 support int version, and enable to compare '3.10' and '3.4'
=> Revert "Fix minversion as string type to pass pytest's version check"

frontend/src/actions/index.js, frontend/src/components/ExperimentsTable.jsx, frontend/src/components/LogVisualizer.jsx, frontend/src/components/LogVisualizerLegend.jsx, frontend/src/components/LogVisualizerTooltip.jsx, frontend/src/containers/PlotContainer.jsx, frontend/src/reducers/index.jsx, frontend/src/store/uiPropTypes.js, frontend/src/styles.css
=> Highlight table row and chart line

frontend/src/components/AxesConfigurator.jsx, frontend/src/components/AxisConfigurator.jsx, frontend/src/components/AxisLogKeySelector.jsx, frontend/src/components/AxisRangeConfigurator.jsx, frontend/src/components/LogVisualizer.jsx, frontend/src/constants/index.js, frontend/src/reducers/index.jsx, frontend/src/store/uiPropTypes.js, frontend/src/utils/index.js
I removed axisConfig's `axisName` . This property is difficult to initialization.
From now on, axisName must be passed as props.
=> Remove axisName from axisConfig

chainerui/models/command.py, chainerui/tasks/crawl_result.py, chainerui/views/result.py, tests/tasks_tests/test_crawl_result.py
fixes #212 
IDs of Command and Snapshot object are set on commit phase, so `db.commit` needs to call before serialization. Additionally fix insertion process, avoid to insert new recorder every time.
=> Avoid to return None type on command or snapshot ID

frontend/src/reducers/index.jsx
I fixed reducers so that updating action does not unnecessarily update the store.
For example, both projectConfig and projectStatus are updated at the same time. I fixed.
And also, all reducers were rewrited that the last line is `return state`.
=> Refactoring reducers

chainerui/summary.py, tests/test_summary.py
fixes #246 
**Example1:**
```
summary.set_out('/path/to/out')
summary.image(array, subdir='sub')
```
The image array will be put on `/path/to/out/sub/image_xxxx.png`
**Example2.**
```
summary.set_out('/path/to/out')
with summary.reporter(subdir='sub1') as r:
r.image(array, subdir='sub2')
```
The image array will be put on `/path/to/out/sub1/sub2/image_xxxx.png`
=> Support sub-directory for asset

frontend/src/components/LogVisualizer.jsx, frontend/src/components/LogVisualizerChart.jsx, frontend/src/components/LogVisualizerLegend.jsx, frontend/src/containers/PlotContainer.jsx
This PR adds checkboxes to `LogVisualizerLegend` .
Using these checkboxes, `LogVisualizerLegend` will take over the features that `LinesConfigurator` in the sidebar currently has.
WIP screenshot
=> Add checkbox to legend

.travis.yml, appveyor.yml
Currently CI job installs Pillow, scipy and other modules for test. To check run ChainerUI on an environment whith installs only required modules, add "Plain install" job.
=> Add plain install job on CI

chainerui/summary.py, requirements.txt, tests/test_summary.py
Please merge #249 first
fixes #248 
This PR allows asset API used by multiple script. For example, training script and evaluating script run together and both processes save images, ChainerUI will show all images at once.
=> Introduce file lock to accept multiple process on assets API

frontend/package-lock.json
- Upgraded lodash to 4.17.11 to avoid the [vulnerability found in lodash < 4.17.11](https://nvd.nist.gov/vuln/detail/CVE-2018-16487).
- Resolved diffs in package-lock.json caused by newer version of npm.
node: v8.11.3, npm: 6.7.0
=> Upgrade lodash to 4.17.11

frontend/src/components/AxesConfigurator.jsx
This PR aims to make rendering on a browser faster by using `React.memo` .
The profiler results below show the difference of rendering time between with and without `React.memo` for `AxesConfigurator` when hovering the mouse over the legend.
**before**
**after**
=> Use React.memo for AxesConfigurator

frontend/src/components/LogVisualizerChart.jsx
Tooltip is not needed when rendering for png download.
This PR disables tooltip in that case.
=> Disable tooltip in png

chainerui/extensions/commands_extension.py
The function no longer exists, so not to call it and fix to snapshot the target manually.
fixes #281
=> Remove _snapshot_object calling

frontend/src/reducers/index.jsx
`removePartialState` will always return the raw state.
I expected it return the tweaked state.
=> Tweaked removePartialState

.travis.yml, appveyor.yml, setup.py, tests/test_render.py
fixes #303 
To control all dependent versions on setup.py
From this PR, windows tests has `flake8` module and need to pass rendering test both win and linux, py36 and py27. Modification is included on this PR.
=> Introduce "test-ci" install mode on setup.py

chainerui/__init__.py, chainerui/client/client.py, tests/client_tests/test_client.py
add `chainerui.log(value)` to support training script which does not use `Trainer`
=> Support send log without Trainer

MANIFEST.in
Run `$ python setup.py` then get "chainerui-0.10.0.tar.gz", which does not include "docs/requirements.txt". This causes installing error on `$ pip install chainerui_0.10.0.tar.gz` 
https://travis-ci.org/chainer/chainerui/jobs/567754471
=> Add docs requirements to MANIFEST

frontend/package-lock.json, frontend/package.json, frontend/webpack.config.js
This PR replaces `babel-polyfill` with `core-js`.
=> Replace babel-polyfill with core-js

frontend/package-lock.json, frontend/package.json, frontend/src/middleware/api.js, frontend/src/reducers/index.jsx, frontend/src/store/configureStore.js
This PR removes `redux-requests` from dependency.
To remove `redux-requests`, functions of `redux-requests` was copied to chainerui.
We need to refactor `middleware/api.js` when we re-write it with typescript.
=> Remove redux requests

frontend/src/actions/index.js, frontend/src/components/AxesConfigurator.jsx, frontend/src/components/LinesConfigurator.jsx, frontend/src/components/LogVisualizerChart.jsx, frontend/src/components/LogVisualizerTooltip.jsx, frontend/src/components/SideBar.jsx, frontend/src/components/SmoothingConfiguratorToggle.jsx, frontend/src/components/SmoothingLinesConfigurator.jsx, frontend/src/components/SmoothingWeightConfigurator.jsx, frontend/src/components/YAxisLogKeySelectorRow.jsx, frontend/src/constants/index.ts, frontend/src/containers/PlotContainer.jsx, frontend/src/reducers/index.jsx, frontend/src/store/types.ts, frontend/src/store/uiPropTypes.ts, frontend/src/utils/index.ts, frontend/src/utils/smoothing.js
=> Line Smoothing

frontend/package-lock.json, frontend/package.json
This PR updates redux to v4.
Redux v4 is needed because it has newer type definitions.
=> use redux v4

.readthedocs.yml, docs/requirements.txt, docs/rtd_conda.yml, docs/source/conf.py
failed by "Command killed due to excessive memory consumption"
- remove conda, because latest Chainer does not have to build chainerx module on readthedocs generation
- use `autodoc_mock_imports` on ignite, becuase torch module is about 600mb
=> Fix to generate docs
