.circleci/config.yml

python2.7 test is failed, it will be fixed after merged #4

add python2.7 environment on CI test

---

chainerui/models/log.py

Render broken main/loss that includes NaN after 3 epoch.
Before:
After:

Add feature to replace NaN with None

---

chainerui/app.py

I added `chainerui server --debug`.

Add debug option into chainerui server command

---

frontend/src/components/AxisRangeConfigurator.jsx
frontend/src/components/result/CommandScheduleForm.jsx
frontend/src/components/result/HyperparamsAdjustFrom.jsx

Fix an error in frontend

---

chainerui/extensions/commands_extension.py
examples/train_mnist.py

When add "stop" operation on "commands" file, this extension stops the training loop. This PR is not included front-end modification.

Add manual stopping on command extension

---

frontend/package-lock.json
frontend/package.json
frontend/src/constants/index.js
frontend/webpack.config.js

Version unification

---

frontend/package-lock.json
frontend/package.json
frontend/src/middleware/api.js
frontend/src/reducers/index.jsx
frontend/src/store/configureStore.js

ref #22 
I modified the redux middleware by using [redux-requests](https://github.com/idolize/redux-requests) .
New middleware allows only one API request at the same time to the same url.

Avoid duplicating API request

---

frontend/src/components/result/Args.jsx

fix key error on result detail page

---

frontend/src/components/LogVisualizer.jsx

Remove dot from chart

---

frontend/src/components/AxesConfigurator.jsx
frontend/src/components/ExperimentsTable.jsx
frontend/src/components/LogVisualizer.jsx
frontend/src/components/ResultRow.jsx
frontend/src/components/XAxisKeySelector.jsx
frontend/src/constants/index.js
frontend/src/containers/PlotContainer.jsx

Add episode and step into x-axis

---

chainerui/__init__.py
chainerui/_version.py
chainerui/app.py
chainerui/utils/db_revision.py
tests/utils_tests/test_db_revision.py

- add DB revision check to:
- `chainerui server`
- `chainerui project create`
- avoid error when create DB on:
- `chainerui db upgrade`
- `chainerui db drop`

Add DB revision check

---

frontend/package-lock.json
frontend/package.json

We use recharts with faster patch!!!
This PR contributes large log data rendering.

Using faster recharts

---

frontend/src/actions/index.js
frontend/src/components/LogVisualizerTooltip.jsx
frontend/src/containers/PlotContainer.jsx
frontend/src/reducers/index.jsx

Resolves #84
- add an action to clear the previous log data
- call that action from `componentDidMount` in `PlotContainer`

Clear plots on location change

---

chainerui/migration/versions/00a907e5780f_add_log_modified_at.py
chainerui/models/result.py
chainerui/tasks/crawl_result.py
tests/tasks_tests/test_crawl_result.py
tests/test_api.py

**required** `pip install msgpack` and `chainerui db upgrade`

loading log file only when file is updated

---

.travis.yml
README.md
docs/source/install.rst

fixes #91 
follow up modern build script, ref [Installing Python Modules](https://docs.python.org/3/installing/index.html#installing-index)

fix document, sample command to install from source

---

requirements.txt

I revert some commits of #43 and #97.
The problem caused by pallets/flask#2193 was solved in #28. (cf. pallets/flask#2549)
I removed the version specification.

Remove version specification

---

chainerui/utils/__init__.py
chainerui/utils/command_item.py
chainerui/utils/commands_state.py
chainerui/utils/log_report.py
chainerui/utils/save_args.py
chainerui/utils/tempdir.py

Fix temporary file permission issue

---

chainerui/tasks/crawl_result.py
tests/tasks_tests/test_crawl_result.py

Result API will return 500 when failed to load some json files. 
So webview cannot get api result if project has error json files.
I tried catch the errors when detect json load error.

Catch error when failed to load json

---

chainerui/models/argument.py

see [this comment](https://github.com/chainer/chainerui/pull/117#issuecomment-399301665)

Add string cast on viewing

---

README.md
docs/source/docker.rst
docs/source/getstart.rst
docs/source/index.rst
docs/source/install.rst

add description about docker start

---

setup.py

ref: https://github.com/chainer/chainer/pull/4846

Prevent from using imp module on setup.py

---

frontend/src/components/LogVisualizer.jsx
frontend/src/utils/index.js

I removed a function with 6 arguments.

Remove buildLineElems as LogVisualizer refactoring

---

frontend/src/components/LogVisualizer.jsx
frontend/src/utils/index.js

Revert "Remove buildLineElems as LogVisualizer refactoring"

---

frontend/src/components/LogVisualizer.jsx

This PR is instead of #129.
If you have a better refactoring, please request PR.

Remove buildLineElems function

---

frontend/src/actions/index.js
frontend/src/components/ExperimentsTable.jsx
frontend/src/components/experiments_table_cell/SubComponent.jsx
frontend/src/components/experiments_table_cell/UnregisterButton.jsx
frontend/src/constants/index.js
frontend/src/containers/PlotContainer.jsx
frontend/src/reducers/index.jsx

I introduced subcomponent for react-table (https://react-table.js.org/#/story/sub-components).
As the first step, the subcomponent has `detail page link`, `stop button`, `take a snapshot button` and `unregister button`.
We can customize the contents of subcomponent later.

Feature/Introduce SubComponent

---

.travis.yml

When add tags, TravisCI deploy sdist module to PyPI automatically.

add auto deploy section

---

chainerui/__init__.py
chainerui/models/asset.py
chainerui/models/bindata.py
chainerui/tasks/collect_images.py
chainerui/views/result_image.py
frontend/src/components/images/ImageList.jsx

prevent from sending base64 encoded binary.

Modify to use image uri path to get resource

---

appveyor.yml
docs/source/install.rst

- travis config has already updated in #147 
- appveyor config is fixed npm verson as 6.x together
- newline code is replaced, CRLF --> LF
fixes #142

update npm version for development

---

frontend/webpack.config.js

Fix bug of #144

---

frontend/src/components/AxisRangeConfigurator.jsx
frontend/src/components/LineConfigurator.jsx

Fix broken checkbox and radiobutton

---

frontend/src/components/LinesConfigurator.jsx

Collapse lines config

---

frontend/src/components/AxisLogKeySelectorRow.jsx
frontend/src/styles.css

Add word-break into logKey

---

frontend/package-lock.json
frontend/package.json

Use recharts v1.3.0

---

frontend/src/components/TruncatedResultName.jsx
frontend/src/components/experiments_table_cell/ResultName.jsx
frontend/src/styles.css

I fixed #127 and #165 .
Before:
After:

Replace truncate function with text-truncate css class

---

frontend/src/styles.css

Fix legend scroll design

---

chainerui/app.py
chainerui/database.py
chainerui/extensions/commands_extension.py

Fix messages output from client

---

.travis.yml
appveyor.yml

ref #162 
- add lint check on frontend source code
- stop CI when autopep8 outputs any differences
- prevent from changing current directory

Add npm lint check on CI

---

chainerui/migration/versions/e3db52a480f8_alter_log_data_type.py
chainerui/models/log.py
requirements.txt
tests/migration_tests/versions_tests/test_alter_log_data_type.py

Remove deprecation argument of msgpack

---

frontend/src/components/LogVisualizer.jsx
frontend/src/components/LogVisualizerTooltip.jsx

Support row highlight on metric

---

frontend/src/components/LogVisualizer.jsx
frontend/src/styles.css

Fixed mouse behavior on active dot

---

frontend/src/components/AxisLogKeySelectorRow.jsx
frontend/src/components/AxisRangeConfigurator.jsx
frontend/src/components/AxisScaleSelector.jsx
frontend/src/components/ExperimentsTableConfigurator.jsx
frontend/src/components/FormControl/Check.jsx
frontend/src/components/FormControl/Select.jsx
frontend/src/components/LineConfigurator.jsx
frontend/src/components/LinesConfiguratorRow.jsx
frontend/src/components/NavigationBar.jsx
frontend/src/components/XAxisKeySelector.jsx
frontend/src/components/result/CommandScheduleForm.jsx
frontend/src/components/result/HyperparamsAdjustFrom.jsx

I added wrapper components for select, checkbox and radio button which we uses frequently in ChainerUI.

Add FormControl's components

---

frontend/src/components/LogVisualizerLegend.jsx

I rewrote `renderItems` as `LogVizualizerLegendItem`.

Rewrite as LogVizualizerLegendItem

---

frontend/src/components/LogVisualizerTooltip.jsx

Rewrite as LogVisualizerTooltipItem

---

frontend/src/components/LogVisualizer.jsx
frontend/src/components/LogVisualizerChart.jsx
frontend/src/store/uiPropTypes.js
frontend/src/styles.css

- added `LogVisualizerChart` component
- fixed issue #226

Split LogVisualizer

---

MANIFEST.in
README.md
setup.py

ref: https://github.com/chainer/chainer/pull/5345

Add long description section for PyPI

---

frontend/src/components/BreadcrumbLink.jsx
frontend/src/components/TruncatedResultName.jsx
frontend/src/containers/PlotContainer.jsx
frontend/src/containers/ResultDetail.jsx

BreadcrumbLink is changed to more simple usage.

Fix breadcrumb

---

docs/source/assets.rst

Fix invalid example code on document

---

frontend/src/containers/AssetsContainer.jsx
frontend/src/containers/PlotContainer.jsx
frontend/src/containers/ProjectsContainer.jsx
frontend/src/containers/ResultDetail.jsx

I fixed container class name and move prop-types definition.

Fix container

---

chainerui/database.py

Remove convert_unicode option on DB setup

---

frontend/package-lock.json
frontend/package.json

After upgrade react-table to v6.9.0, We founded react-table was broken when result grouping.
v6.9.2 will resolve this issue.

Upgrade react-table to v6.9.2

---

frontend/src/components/LogVisualizerChart.jsx

Fix disappered tooltip

---

frontend/package-lock.json
frontend/package.json

Upgrade jquery

---

chainerui/client/client.py
chainerui/utils/save_args.py
tests/client_tests/test_client.py

Add condition param on client

---

frontend/src/components/result/ResultSummary.jsx

I fixed an issue that the results page was not displayed, when reload.

Fix results page

---

frontend/src/components/AssetsTable.jsx
frontend/src/store/uiPropTypes.js

I fixed an issue that the assets page was not displayed, after merged #287.

Fix assets page

---

frontend/package-lock.json

Upgrade lodash

---

.travis.yml
appveyor.yml
docs/source/install.rst
requirements.txt

change default version of Python

Support Python3.7, add CI test

---

chainerui/models/result.py

To be more static to show "last log" on the table.

Add order-by option

---

chainerui/client/client.py
docs/source/reference/module.rst

Add web client API documentation

---

.travis.yml

to notify error before release action

Add sdist check on CI

---

.travis.yml
chainerui/client/client.py
chainerui/summary.py
docs/source/conf.py
setup.py

Introduce doctest

---

frontend/src/components/ExperimentsTable.jsx

Handling empty log

---

frontend/package-lock.json
frontend/package.json
frontend/webpack.config.js

1. remove uglifyjs plugin, this webpack plugin is deprecated
1. use terser plugin on webpack config, this webpack plugin has already installed
1. reinstall webpack@4.39.2, to upgrade serialize-javascript for fixing https://github.com/advisories/GHSA-h9rv-jmmf-4pgx

stop to use uglifyjs, use terser

---

frontend/src/actions/status.ts
frontend/src/components/SelectedResultTools.jsx
frontend/src/containers/PlotContainer.jsx
frontend/src/reducers/statusReducer.ts
frontend/src/store/types.ts
frontend/src/store/uiPropTypes.ts

This p-r provides a button to undo for removed/restored results.
Any feedbacks are welcome on implementation and user experience.

Undo button for updated results
